/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.mycompany.chaponibus.view.screens;

import br.com.mycompany.chaponibus.dao.UsuarioDAO;
import br.com.mycompany.chaponibus.model.Usuario;
import br.com.mycompany.chaponibus.util.Sessao;
import br.com.mycompany.chaponibus.view.JFEstruturaCelular;
import com.formdev.flatlaf.FlatClientProperties;
import static java.awt.EventQueue.invokeLater;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.net.URL;
import static java.util.logging.Level.WARNING;

/**
 *
 * @author ce498
 */
public class JPLogin extends javax.swing.JPanel {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JPLogin.class.getName());
    private JFEstruturaCelular telaPrincipal;
    private final UsuarioDAO usuarioDAO;
    
    public JPLogin(JFEstruturaCelular tela) {
        this.telaPrincipal = tela;
        this.usuarioDAO = new UsuarioDAO();
        initComponents();
        
        jLAvisoSenha.setVisible(false);
        jLAvisoUsuario.setVisible(false);
        
        this.setBackground(new java.awt.Color(21,80,150));
        
        jPCardBranco.putClientProperty("FlatLaf.style", "arc: 30");
        
        jTFUsuario.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, telaPrincipal.createIcon("/br/com/mycompany/chaponibus/assets/usuario.png", 16));
        jTFUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.GRAY));
        jTFUsuario.setOpaque(false);
        
        jPFSenha.putClientProperty(FlatClientProperties.STYLE, "showRevealButton: true;");
        jPFSenha.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, telaPrincipal.createIcon("/br/com/mycompany/chaponibus/assets/chave.png", 16));
        jPFSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.GRAY));
        jPFSenha.setOpaque(false);
        
        jBCriarConta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.GRAY));
        
        jBVoltar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.GRAY));
        jBVoltar.setIcon(telaPrincipal.createIcon("/br/com/mycompany/chaponibus/assets/flecha.png", 32));
    }
    
    public void reiniciarTela() {
        jTFUsuario.setText("");
        jPFSenha.setText("");

        jLAvisoUsuario.setVisible(false);
        jLAvisoSenha.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCardBranco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPFSenha = new javax.swing.JPasswordField();
        jTFUsuario = new javax.swing.JTextField();
        jBLogin = new javax.swing.JButton();
        jBCriarConta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLAvisoUsuario = new javax.swing.JLabel();
        jLAvisoSenha = new javax.swing.JLabel();
        jPCabecalho = new javax.swing.JPanel();
        jBVoltar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPCardBranco.setBackground(new java.awt.Color(244, 247, 249));
        jPCardBranco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPCardBranco.setEnabled(false);
        jPCardBranco.setPreferredSize(new java.awt.Dimension(375, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Usuário");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Senha");

        jPFSenha.addActionListener(this::jPFSenhaActionPerformed);
        jPFSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPFSenhaKeyTyped(evt);
            }
        });

        jTFUsuario.addActionListener(this::jTFUsuarioActionPerformed);
        jTFUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFUsuarioKeyTyped(evt);
            }
        });

        jBLogin.setBackground(new java.awt.Color(21, 80, 150));
        jBLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBLogin.setForeground(new java.awt.Color(244, 247, 249));
        jBLogin.setText("Login");
        jBLogin.addActionListener(this::jBLoginActionPerformed);

        jBCriarConta.setBackground(new java.awt.Color(244, 247, 249));
        jBCriarConta.setForeground(new java.awt.Color(21, 80, 150));
        jBCriarConta.setText("Criar conta");
        jBCriarConta.addActionListener(this::jBCriarContaActionPerformed);

        jLabel3.setText("Não tem uma conta?");

        jLAvisoUsuario.setForeground(new java.awt.Color(255, 44, 44));
        jLAvisoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAvisoUsuario.setText("Informe um usuário");

        jLAvisoSenha.setForeground(new java.awt.Color(255, 44, 44));
        jLAvisoSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAvisoSenha.setText("Informe uma senha");

        javax.swing.GroupLayout jPCardBrancoLayout = new javax.swing.GroupLayout(jPCardBranco);
        jPCardBranco.setLayout(jPCardBrancoLayout);
        jPCardBrancoLayout.setHorizontalGroup(
            jPCardBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCardBrancoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPCardBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCardBrancoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCardBrancoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPCardBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPFSenha)
                        .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCardBrancoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLAvisoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCardBrancoLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLAvisoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPCardBrancoLayout.setVerticalGroup(
            jPCardBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCardBrancoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAvisoUsuario)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAvisoSenha)
                .addGap(34, 34, 34)
                .addComponent(jBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCardBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jBCriarConta))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        add(jPCardBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 375, -1));
        jPCardBranco.getAccessibleContext().setAccessibleDescription("");

        jPCabecalho.setBackground(new java.awt.Color(21, 80, 150));
        jPCabecalho.setPreferredSize(new java.awt.Dimension(375, 250));

        jBVoltar.setBackground(new java.awt.Color(21, 80, 150));
        jBVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBVoltar.setForeground(new java.awt.Color(244, 247, 249));
        jBVoltar.addActionListener(this::jBVoltarActionPerformed);

        javax.swing.GroupLayout jPCabecalhoLayout = new javax.swing.GroupLayout(jPCabecalho);
        jPCabecalho.setLayout(jPCabecalhoLayout);
        jPCabecalhoLayout.setHorizontalGroup(
            jPCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPCabecalhoLayout.setVerticalGroup(
            jPCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        add(jPCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 375, 200));
    }// </editor-fold>//GEN-END:initComponents
    
    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        if (jTFUsuario.getText().trim().isEmpty()) {
            jLAvisoUsuario.setVisible(true);
            jTFUsuario.requestFocus();
            return;
        }
        
        String senha = new String(jPFSenha.getPassword());
        
        if (senha.trim().isEmpty()) {
            jLAvisoSenha.setVisible(true);
            jPFSenha.requestFocus();
            return;
        }
        
        jBLogin.setEnabled(false);
        jBLogin.setText("");
        
        try {
            URL imgURL = getClass().getResource("/br/com/mycompany/chaponibus/assets/loading.gif");
            if (imgURL != null) {
                ImageIcon iconeOriginal = new ImageIcon(imgURL);
                Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(16, 16, Image.SCALE_DEFAULT);
                jBLogin.setIcon(new ImageIcon(imagemRedimensionada));
            } else {
                jBLogin.setText("Carregando...");
            }
        } catch (Exception e) {
            logger.log(WARNING, "Não foi possível carregar o GIF de loading", e);
        }
        
        new Thread(() -> {
            Usuario validaUsuario = usuarioDAO.validarLogin(jTFUsuario.getText(), senha);
            
            invokeLater(() -> {
                if (validaUsuario != null) {
                    Sessao.conectar(validaUsuario);
                    
                    telaPrincipal.showToast(telaPrincipal, "Login realizado com sucesso!", 21, 80, 150);
                    
                    jBLogin.setIcon(null);
                    jBLogin.setEnabled(true);
                    jBLogin.setText("Login");
                    
                    jTFUsuario.setText("");
                    jPFSenha.setText("");
                    telaPrincipal.mudarTela("cardMapa");
                } else {
                    telaPrincipal.showToast(telaPrincipal, "Informe um usuário e senha válidos", 255, 44, 44);
                    
                    jBLogin.setIcon(null);
                    jBLogin.setEnabled(true);
                    jBLogin.setText("Login");
                    
                    jPFSenha.setText("");
                    jPFSenha.requestFocus();
                }
            });
        }).start();
    }//GEN-LAST:event_jBLoginActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        jTFUsuario.setText("");
        jPFSenha.setText("");
        telaPrincipal.mudarTela("cardMapa");
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuarioActionPerformed
        jLAvisoUsuario.setVisible(false);
    }//GEN-LAST:event_jTFUsuarioActionPerformed

    private void jPFSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFSenhaActionPerformed
        jLAvisoSenha.setVisible(false);
    }//GEN-LAST:event_jPFSenhaActionPerformed

    private void jTFUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFUsuarioKeyTyped
        jLAvisoUsuario.setVisible(false);
    }//GEN-LAST:event_jTFUsuarioKeyTyped

    private void jPFSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFSenhaKeyTyped
        jLAvisoSenha.setVisible(false);
    }//GEN-LAST:event_jPFSenhaKeyTyped

    private void jBCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCriarContaActionPerformed
        telaPrincipal.mudarTela("cardCadastro");
    }//GEN-LAST:event_jBCriarContaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCriarConta;
    private javax.swing.JButton jBLogin;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLAvisoSenha;
    private javax.swing.JLabel jLAvisoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPCabecalho;
    private javax.swing.JPanel jPCardBranco;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
