/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.mycompany.chaponibus.view;

import br.com.mycompany.chaponibus.view.screens.JPLogin;
import br.com.mycompany.chaponibus.view.screens.JPMapa;
import java.awt.CardLayout;

/**
 *
 * @author ce498
 */
public class JFEstruturaCelular extends javax.swing.JFrame {
    


    /**
     * Creates new form JFEstruturaCelular
     */
    public JFEstruturaCelular() {
        initComponents();
        
        javax.swing.JPanel painelFoco = new javax.swing.JPanel();
        this.add(painelFoco);
        painelFoco.requestFocusInWindow();

        this.setSize(390, 800);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        jPPainelConteudo.setLayout(new java.awt.CardLayout());
        
        JPMapa meuMapa = new JPMapa(this);
        JPLogin telaLogin = new JPLogin(this);
        
        jPPainelConteudo.add(meuMapa, "cardMapa");
        jPPainelConteudo.add(telaLogin, "cardLogin");
        jPPainelConteudo.add(cardPerfil, "cardPerfil");
        jPPainelConteudo.add(cardCadastro, "cardCadastro");
        
        mudarTela("cardMapa");
    }
    
    public void mudarTela(String nomeDaTela) {
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, nomeDaTela);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPainelConteudo = new javax.swing.JPanel();
        cardPerfil = new br.com.mycompany.chaponibus.view.screens.JPPerfil();
        cardCadastro = new br.com.mycompany.chaponibus.view.screens.JPCadastro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPPainelConteudo.setMaximumSize(new java.awt.Dimension(390, 800));
        jPPainelConteudo.setMinimumSize(new java.awt.Dimension(390, 800));
        jPPainelConteudo.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout cardPerfilLayout = new javax.swing.GroupLayout(cardPerfil);
        cardPerfil.setLayout(cardPerfilLayout);
        cardPerfilLayout.setHorizontalGroup(
            cardPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        cardPerfilLayout.setVerticalGroup(
            cardPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPPainelConteudo.add(cardPerfil, "cardPerfil");

        javax.swing.GroupLayout cardCadastroLayout = new javax.swing.GroupLayout(cardCadastro);
        cardCadastro.setLayout(cardCadastroLayout);
        cardCadastroLayout.setHorizontalGroup(
            cardCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        cardCadastroLayout.setVerticalGroup(
            cardCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPPainelConteudo.add(cardCadastro, "cardCadastro");

        getContentPane().add(jPPainelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFEstruturaCelular().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.mycompany.chaponibus.view.screens.JPCadastro cardCadastro;
    private br.com.mycompany.chaponibus.view.screens.JPPerfil cardPerfil;
    private javax.swing.JPanel jPPainelConteudo;
    // End of variables declaration//GEN-END:variables
}
