/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.mycompany.chaponibus.view;

import java.awt.CardLayout;

/**
 *
 * @author ce498
 */
public class JFEstruturaCelular extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFEstruturaCelular.class.getName());

    /**
     * Creates new form JFEstruturaCelular
     */
    public JFEstruturaCelular() {
        initComponents();
        this.setSize(390, 800);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        jPPainelConteudo.removeAll();
        jPPainelConteudo.setLayout(new java.awt.CardLayout());
        
        cardLogin = new br.com.mycompany.chaponibus.view.screens.JPLogin();
        cardMapa = new br.com.mycompany.chaponibus.view.screens.JPMapa();
        cardPerfil = new br.com.mycompany.chaponibus.view.screens.JPPerfil();
        
        jPPainelConteudo.add(cardLogin, "cardLogin");
        jPPainelConteudo.add(cardMapa, "cardMapa");
        jPPainelConteudo.add(cardPerfil, "cardPerfil");
        
        this.getContentPane().setLayout(new java.awt.BorderLayout());
        this.getContentPane().add(jPPainelConteudo, java.awt.BorderLayout.CENTER);
        
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardMapa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPainelConteudo = new javax.swing.JPanel();
        cardLogin = new br.com.mycompany.chaponibus.view.screens.JPLogin();
        cardMapa = new br.com.mycompany.chaponibus.view.screens.JPMapa();
        cardPerfil = new br.com.mycompany.chaponibus.view.screens.JPPerfil();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPPainelConteudo.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout cardLoginLayout = new javax.swing.GroupLayout(cardLogin);
        cardLogin.setLayout(cardLoginLayout);
        cardLoginLayout.setHorizontalGroup(
            cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        cardLoginLayout.setVerticalGroup(
            cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jPPainelConteudo.add(cardLogin, "card2");

        javax.swing.GroupLayout cardMapaLayout = new javax.swing.GroupLayout(cardMapa);
        cardMapa.setLayout(cardMapaLayout);
        cardMapaLayout.setHorizontalGroup(
            cardMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        cardMapaLayout.setVerticalGroup(
            cardMapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jPPainelConteudo.add(cardMapa, "card3");

        javax.swing.GroupLayout cardPerfilLayout = new javax.swing.GroupLayout(cardPerfil);
        cardPerfil.setLayout(cardPerfilLayout);
        cardPerfilLayout.setHorizontalGroup(
            cardPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        cardPerfilLayout.setVerticalGroup(
            cardPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jPPainelConteudo.add(cardPerfil, "card4");

        getContentPane().add(jPPainelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFEstruturaCelular().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.mycompany.chaponibus.view.screens.JPLogin cardLogin;
    private br.com.mycompany.chaponibus.view.screens.JPMapa cardMapa;
    private br.com.mycompany.chaponibus.view.screens.JPPerfil cardPerfil;
    private javax.swing.JPanel jPPainelConteudo;
    // End of variables declaration//GEN-END:variables
}
