/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view.usuarios;

import br.com.mycompany.chaponibus.admin.dao.UsuarioDAO;
import br.com.mycompany.chaponibus.admin.model.Usuario;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos62347296
 */
public class JDCadastrarUsuario extends javax.swing.JDialog {
    
    private final UsuarioDAO usuarioDAO;
    private Usuario usuarioEmEdicao = null;
    
    private boolean salvouComSucesso = false;

    public JDCadastrarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        jLTitulo.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/user-plus-solid.png", 32));
        jLTitulo.setIconTextGap(15);
        
        jLInfo.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/circle-info-solid.png", 24));
        jLInfo.putClientProperty("FlatLaf.style", "arc: 15; border: 4, 12, 4, 12");
        jLInfo.setIconTextGap(8);
        
        jBCadastrar.putClientProperty("JButton.buttonType", "borderless");
        jBCancelar.putClientProperty("JButton.buttonType", "borderless");
        
        this.usuarioDAO = new UsuarioDAO();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        this.setResizable(false);
        this.setLocationRelativeTo(parent);
    }
    
    public JDCadastrarUsuario(java.awt.Frame parent, boolean modal, Usuario usuario) {
        this(parent, modal);
        
        this.usuarioEmEdicao = usuario;
        jTFUsuario.setText(usuario.getUsername());
        jCBPerfil.setSelectedItem(usuario.getRole());
        
        jTFUsuario.setEditable(false);
        jBCadastrar.setText("Atualizar");
    }
    
    public boolean isSalvouComSucesso() {
        return salvouComSucesso;
    }
    
    public ImageIcon createIcon(String endereco, int tamanho) {
        ImageIcon iconeOriginal = new ImageIcon(getClass().getResource(endereco));
        Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(tamanho, tamanho, Image.SCALE_SMOOTH);
        ImageIcon iconeUsuario = new ImageIcon(imagemRedimensionada);
        return iconeUsuario;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCabecalho = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPPrincipal = new javax.swing.JPanel();
        jLUsuario = new javax.swing.JLabel();
        jLPerfil = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jCBPerfil = new javax.swing.JComboBox<>();
        jLInfo = new javax.swing.JLabel();
        jBCadastrar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPCabecalho.setBackground(new java.awt.Color(21, 80, 150));
        jPCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("Cadastro de Novo Administrador");
        jPCabecalho.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Preencha as informações para criar um novo acesso ao sistema.");
        jPCabecalho.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        getContentPane().add(jPCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 90));

        jPPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLUsuario.setText("Usuário");
        jPPrincipal.add(jLUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLPerfil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLPerfil.setText("Perfil");
        jPPrincipal.add(jLPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPPrincipal.add(jTFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 430, 40));

        jCBPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Super Administrador" }));
        jPPrincipal.add(jCBPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 430, 40));

        jLInfo.setBackground(new java.awt.Color(236, 240, 255));
        jLInfo.setText("O novo administrador deverá alterar sua senha no primeiro login.");
        jPPrincipal.add(jLInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 430, 40));

        jBCadastrar.setBackground(new java.awt.Color(248, 158, 49));
        jBCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jBCadastrar.setText("Salvar Administrador");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });
        jPPrincipal.add(jBCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 430, 50));

        jBCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPPrincipal.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 430, 50));

        getContentPane().add(jPPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 470, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        if (jTFUsuario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um usuário válido", "Aviso", JOptionPane.WARNING_MESSAGE);
            jTFUsuario.requestFocus();
            return;
        }

        if (jCBPerfil.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um perfil de acesso", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String username = jTFUsuario.getText().trim();
        String perfil = jCBPerfil.getSelectedItem().toString();
        
        if (usuarioEmEdicao == null) {
            if (usuarioDAO.procurarUsuario(username) != null) {
                JOptionPane.showMessageDialog(this, "Esse nome de usuário já está cadastrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                jTFUsuario.requestFocus();
                return;
            }
            
            Usuario novoUsuario = new Usuario(
                username,
                "123456",
                perfil,
                true
            );
            
            try {
                usuarioDAO.salvar(novoUsuario);

                JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                this.salvouComSucesso = true;
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar no banco de dados: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            usuarioEmEdicao.setRole(perfil);
            
            try {
                usuarioDAO.atualizar(usuarioEmEdicao, usuarioEmEdicao.getUsername());

                JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                
                this.salvouComSucesso = true;
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar no banco de dados: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        jTFUsuario.setText("");
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(JDCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            JDCadastrarUsuario dialog = new JDCadastrarUsuario(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    // Corrigido: Apenas fecha o Dialog no teste individual, sem matar o sistema principal
                    dialog.dispose(); 
                }
            });
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox<String> jCBPerfil;
    private javax.swing.JLabel jLInfo;
    private javax.swing.JLabel jLPerfil;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPCabecalho;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
