/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view.usuarios;

import br.com.mycompany.chaponibus.admin.dao.UsuarioDAO;
import br.com.mycompany.chaponibus.admin.model.Usuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Window;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author carlos62347296
 */
public class JPUsuarios extends javax.swing.JPanel {
    
    private final UsuarioDAO usuarioDAO;
    
    int ultimaLinhaSelecionada = -1; 

    /**
     * Creates new form JPCadastroDeUsuario
     */
    
        public JPUsuarios() {
        initComponents();
        
        this.usuarioDAO = new UsuarioDAO();
        
        preencherTabela();
        
        jBExcluir.setVisible(false);
        jBEditar.setVisible(false);
        
        jBEditar.setToolTipText("Editar usuário selecionado");
        jBExcluir.setToolTipText("Excluir usuário selecionado");
        
        int iconSize = 20;
        
        jBEditar.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/edit_icon.png", iconSize));
        jBExcluir.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/excluir_icon.png", iconSize));
        
        jTUsuarios.setRowHeight(30);
        jTUsuarios.setShowHorizontalLines(true);
        jTUsuarios.setShowVerticalLines(false);
        jTUsuarios.setGridColor(new Color(230, 235, 240));
        jTUsuarios.putClientProperty("FlatLaf.style", "showCellFocusIndicator: false");
        
        jTUsuarios.getTableHeader().setPreferredSize(new Dimension(0, 45));
        jTUsuarios.getTableHeader().putClientProperty("FlatLaf.style", 
                "background: #f1f3f5;" +
                "foreground: #212529;" +
                "font: bold 16;" +
                "separatorColor: #f1f3f5"
        );
    }
    
    public void preencherTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTUsuarios.getModel();
        
        modelo.setNumRows(0);
        
        try {
            List<Usuario> lista = usuarioDAO.listarTodos();
        
            for (Usuario u : lista) {
                if (u.getRole().equals("Administrador") || u.getRole().equals("Super Administrador")) {
                    modelo.addRow(new Object[] {
                        u.getUsername(),
                        u.getRole()
                    });
                }
            }
            
            jBExcluir.setVisible(false);
            jBEditar.setVisible(false);
            jTUsuarios.clearSelection();
            this.ultimaLinhaSelecionada = -1;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }   
    }
    
    private void ConfigurarVisual (){
        jBEditar.putClientProperty("FlatLaf.style", "");
      
      
    }
    
    public ImageIcon createIcon(String endereco, int tamanho) {
        ImageIcon iconeOriginal = new ImageIcon(getClass().getResource(endereco));
        Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(tamanho, tamanho, Image.SCALE_SMOOTH);
        ImageIcon iconeUsuario = new ImageIcon(imagemRedimensionada);
        return iconeUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCabecalho = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPPrincipal = new javax.swing.JPanel();
        jBEditar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();
        jBCadastrarUsuario = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPCabecalho.setBackground(new java.awt.Color(255, 255, 255));
        jPCabecalho.setPreferredSize(new java.awt.Dimension(1110, 80));
        jPCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 80, 150));
        jLabel2.setText("Gestão de Usuários Administradores");
        jPCabecalho.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, -1));

        add(jPCabecalho, java.awt.BorderLayout.PAGE_START);

        jPPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jBEditar.setBackground(new java.awt.Color(208, 125, 7));
        jBEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBExcluir.setBackground(new java.awt.Color(204, 0, 0));
        jBExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Usuario", "Papel"
            }
        ) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        jTUsuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTUsuarios.getTableHeader().setReorderingAllowed(false);
        // Alinha o redimensionamento automático
        jTUsuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        // Coluna 1 (Papel) terá um tamanho fixo e controlado
        jTUsuarios.getColumnModel().getColumn(1).setPreferredWidth(150);

        // Coluna 0 (Usuario) vai engolir todo o resto do espaço da tabela automaticamente
        jTUsuarios.getColumnModel().getColumn(0).setPreferredWidth(300);

        // Impede o usuário de arrastar e reordenar as colunas de lugar (ex: puxar "Papel" para antes de "Usuario")
        jTUsuarios.getTableHeader().setReorderingAllowed(false);

        // Impede o usuário de mudar a largura das colunas arrastando com o mouse
        jTUsuarios.getTableHeader().setResizingAllowed(false);
        jTUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTUsuarios);

        jBCadastrarUsuario.setBackground(new java.awt.Color(21, 80, 150));
        jBCadastrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBCadastrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jBCadastrarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCadastrarUsuario.setLabel("Novo Usuário");
        jBCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCadastrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        add(jPPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarUsuarioActionPerformed
        Window janelaMae = SwingUtilities.getWindowAncestor(this);
        
        Frame framePai = (janelaMae instanceof Frame) ? (Frame) janelaMae : null;
        
        JDCadastrarUsuario telaCadastrarUsuario = new JDCadastrarUsuario(framePai, true);
        
        telaCadastrarUsuario.setLocationRelativeTo(janelaMae);
        telaCadastrarUsuario.setVisible(true);
        
        if (telaCadastrarUsuario.isSalvouComSucesso()) {
            preencherTabela();
        }
    }//GEN-LAST:event_jBCadastrarUsuarioActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int linha = jTUsuarios.getSelectedRow();
        if (linha != -1) {
            String username = jTUsuarios.getValueAt(linha, 0).toString();
            
            int confirmacao = JOptionPane.showConfirmDialog(this, 
                    "Deseja realmente excluir o usuário " + username + "?",
                    "", JOptionPane.YES_NO_OPTION);
            
            if (confirmacao == JOptionPane.YES_OPTION) {
                try {
                    usuarioDAO.excluir(username);
                    JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    preencherTabela();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir usuário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsuariosMouseClicked
        int linha = jTUsuarios.getSelectedRow();
        
        if (linha == -1) {
            jBExcluir.setVisible(false);
            jBEditar.setVisible(false);
            ultimaLinhaSelecionada = -1;
            return;
        }
        
        if (evt.getClickCount() == 2) {
            jBEditarActionPerformed(null);
            return;
        }
        
        if (linha == ultimaLinhaSelecionada) {
            jBExcluir.setVisible(false);
            jBEditar.setVisible(false);
            jTUsuarios.clearSelection(); 
            ultimaLinhaSelecionada = -1;
        } else {
            jBExcluir.setVisible(true);
            jBEditar.setVisible(true);
            ultimaLinhaSelecionada = linha;
        }
    }//GEN-LAST:event_jTUsuariosMouseClicked

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        int linha = jTUsuarios.getSelectedRow();
        
        if (linha != -1) {
            String username = jTUsuarios.getValueAt(linha, 0).toString();
            
            Usuario usuario = usuarioDAO.procurarUsuario(username);
            
            if (usuario != null) {
                Window janelaMae = SwingUtilities.getWindowAncestor(this);
                Frame framePai = (janelaMae instanceof Frame) ? (Frame) janelaMae : null;

                JDCadastrarUsuario telaEditarUsuario = new JDCadastrarUsuario(framePai, true, usuario);
                telaEditarUsuario.setLocationRelativeTo(janelaMae);
                telaEditarUsuario.setVisible(true);

                if (telaEditarUsuario.isSalvouComSucesso()) {
                    preencherTabela();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro: Nenhum usuário encontrado ou selecionado", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarUsuario;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPCabecalho;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTUsuarios;
    // End of variables declaration//GEN-END:variables
}
