/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view.login;

import br.com.mycompany.chaponibus.admin.dao.UsuarioDAO;
import br.com.mycompany.chaponibus.admin.util.Sessao;
import br.com.mycompany.chaponibus.admin.model.Usuario;
import br.com.mycompany.chaponibus.admin.view.JFTelaEstrutural;
import com.formdev.flatlaf.FlatClientProperties;
import static java.awt.EventQueue.invokeLater;
import java.awt.Image;
import java.net.URL;
import static java.util.logging.Level.WARNING;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author ce498
 */
public class JFLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFLogin.class.getName());
    private final UsuarioDAO usuarioDAO;

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
        getContentPane().setBackground(new Color(240,240,240));
        getContentPane().setBackground(new Color(240,240,240));
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Chapônibus");
        this.usuarioDAO = new UsuarioDAO();
        
        jLabel3.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/logo-fundo-branco.png", 64, 87));
        
        jTFUsuario.requestFocusInWindow();
        jTFUsuario.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, createIcon("/br/com/mycompany/chaponibus/admin/assets/usuario.png", 16, 16));
        jTFUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.GRAY));
        jTFUsuario.setOpaque(false);
        jTFUsuario.putClientProperty("FlatLaf.style", "iconTextGap: 8; margin: 6, 10, 6, 10");
        
        jPFSenha.putClientProperty(FlatClientProperties.STYLE, "showRevealButton: true;");
        jPFSenha.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, createIcon("/br/com/mycompany/chaponibus/admin/assets/chave.png", 16, 16));
        jPFSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.Color.GRAY));
        jPFSenha.setOpaque(false);
        jPFSenha.putClientProperty("FlatLaf.style", "iconTextGap: 8; margin: 6, 10, 6, 10");
    }
    
    public ImageIcon createIcon(String endereco, int x, int y) {
        ImageIcon iconeOriginal = new ImageIcon(getClass().getResource(endereco));
        Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(x, y, Image.SCALE_SMOOTH);
        ImageIcon iconeUsuario = new ImageIcon(imagemRedimensionada);
        return iconeUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTFUsuario = new javax.swing.JTextField();
        jLUsuario = new javax.swing.JLabel();
        jLSenha = new javax.swing.JLabel();
        jPFSenha = new javax.swing.JPasswordField();
        jBLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 48, 99));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Bem vindo ao");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Chapônibus!");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 150, -1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 70, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 402, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFUsuario.addActionListener(this::jTFUsuarioActionPerformed);
        jPanel3.add(jTFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 320, 30));

        jLUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLUsuario.setText("Usuário");
        jLUsuario.setToolTipText("");
        jPanel3.add(jLUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, -1));

        jLSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLSenha.setText("Senha");
        jPanel3.add(jLSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jPFSenha.addActionListener(this::jPFSenhaActionPerformed);
        jPanel3.add(jPFSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, 30));

        jBLogin.setBackground(new java.awt.Color(248, 158, 49));
        jBLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBLogin.setForeground(new java.awt.Color(255, 255, 255));
        jBLogin.setText("Entrar");
        jBLogin.addActionListener(this::jBLoginActionPerformed);
        jPanel3.add(jBLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 320, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 400, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPFSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFSenhaActionPerformed
        efetuarLogin();
    }//GEN-LAST:event_jPFSenhaActionPerformed

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        efetuarLogin();
    }//GEN-LAST:event_jBLoginActionPerformed

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuarioActionPerformed
        efetuarLogin();
    }//GEN-LAST:event_jTFUsuarioActionPerformed
    
    private void efetuarLogin() {
        if (jTFUsuario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira um usuário");
            jTFUsuario.requestFocus();
            return;
        }
        
        String senha = new String(jPFSenha.getPassword());
        
        if (senha.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira uma senha");
            jPFSenha.requestFocus();
            return;
        }
        
        jBLogin.setEnabled(false);
        jBLogin.setText("");
        
        try {
            URL imgURL = getClass().getResource("/br/com/mycompany/chaponibus/admin/assets/loading.gif");
            if (imgURL != null) {
                ImageIcon iconeOriginal = new ImageIcon(imgURL);
                Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(16, 16, Image.SCALE_DEFAULT);
                jBLogin.setIcon(new ImageIcon(imagemRedimensionada));
            } else {
                jBLogin.setText("Carregando...");
            }
        } catch (Exception e) {
            logger.log(WARNING, "Não foi possível carregar o GIF de loading", e);
        }
        
        new Thread(() -> {
            Usuario validaUsuario = usuarioDAO.validarLogin(jTFUsuario.getText(), senha);
            
            invokeLater(() -> {
                if (validaUsuario != null) {
                    Sessao.conectar(validaUsuario);
                    
                    jBLogin.setIcon(null);
                    
                    if (validaUsuario.isPrimeiroAcesso()) {
                         new JFTrocarSenhaPrimeiroAcesso(validaUsuario).setVisible(true);
                         this.dispose();
                    } else {
                    JOptionPane.showMessageDialog(null, "Bem-vindo, " + validaUsuario.getUsername() + "!");
                    
                    new JFTelaEstrutural().setVisible(true);
                    this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Informe um usuário e senha válidos");
                    
                    jBLogin.setIcon(null);
                    jBLogin.setEnabled(true);
                    jBLogin.setText("Login");
                    
                    jPFSenha.setText("");
                    jPFSenha.requestFocus();
                }
            });
        }).start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLogin;
    private javax.swing.JLabel jLSenha;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}