/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view.login;

import br.com.mycompany.chaponibus.admin.model.Usuario;
import br.com.mycompany.chaponibus.admin.dao.UsuarioDAO;
import br.com.mycompany.chaponibus.admin.util.Sessao;
import br.com.mycompany.chaponibus.admin.view.JFTelaEstrutural;
import java.awt.Image;
import java.net.URL;
import static java.util.logging.Level.WARNING;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Pichau
 */


public class JFTrocarSenhaPrimeiroAcesso extends javax.swing.JFrame { 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFLogin.class.getName());
    private Usuario validaUsuario;
    private UsuarioDAO usuarioDAO;

    /**
     * Creates new form JFTrocarSenhaPrimeiroAcesso
     */
    public JFTrocarSenhaPrimeiroAcesso(Usuario usuarioLogado) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.validaUsuario = usuarioLogado;
        this.usuarioDAO = new UsuarioDAO();
        
        jLabel3.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/logo-fundo-branco.png", 64, 87));
    }
    
    public ImageIcon createIcon(String endereco, int x, int y) {
        ImageIcon iconeOriginal = new ImageIcon(getClass().getResource(endereco));
        Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(x, y, Image.SCALE_SMOOTH);
        ImageIcon iconeUsuario = new ImageIcon(imagemRedimensionada);
        return iconeUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCabecalho = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPFSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPFSenha1 = new javax.swing.JPasswordField();
        jBLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCabecalho.setBackground(new java.awt.Color(0, 48, 99));
        jLCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCabecalho.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Primeiro acesso");
        jLCabecalho.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 470, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Para sua segurança, crie uma nova senha");
        jLCabecalho.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 470, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("para continuar acessando o painel administrativo.");
        jLCabecalho.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 470, -1));

        getContentPane().add(jLCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 190));

        jLPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jLPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Confirmar Nova Senha");
        jLPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jPFSenha.addActionListener(this::jPFSenhaActionPerformed);
        jLPrincipal.add(jPFSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 410, 40));

        jLabel6.setText("Nova Senha");
        jLPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPFSenha1.addActionListener(this::jPFSenha1ActionPerformed);
        jLPrincipal.add(jPFSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 410, 40));

        jBLogin.setBackground(new java.awt.Color(248, 158, 49));
        jBLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBLogin.setForeground(new java.awt.Color(255, 255, 255));
        jBLogin.setText("Entrar");
        jBLogin.addActionListener(this::jBLoginActionPerformed);
        jLPrincipal.add(jBLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 410, 50));

        getContentPane().add(jLPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 470, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPFSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFSenhaActionPerformed

    }//GEN-LAST:event_jPFSenhaActionPerformed

    private void jPFSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPFSenha1ActionPerformed

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        String senhaNova = new String(jPFSenha1.getPassword());
        String confirmacaoSenhaNova = new String(jPFSenha.getPassword());
        
        if (senhaNova.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira a sua nova senha");
            jPFSenha1.requestFocus();
            return;
        }
        
        if (confirmacaoSenhaNova.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira a confirmação da sua nova senha");
            jPFSenha.requestFocus();
            return;
        }
        
        if (!senhaNova.trim().equals(confirmacaoSenhaNova.trim())) {
            JOptionPane.showMessageDialog(null, "As duas senhas informadas devem ser iguais");
            jPFSenha.requestFocus();
            return;
        }
        
        validaUsuario.setPassword(senhaNova);
        validaUsuario.setPrimeiroAcesso(false);
        
        try {
            URL imgURL = getClass().getResource("/br/com/mycompany/chaponibus/admin/assets/loading.gif");
            if (imgURL != null) {
                ImageIcon iconeOriginal = new ImageIcon(imgURL);
                Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(16, 16, Image.SCALE_DEFAULT);
                jBLogin.setIcon(new ImageIcon(imagemRedimensionada));
            } else {
                jBLogin.setText("Carregando...");
            }
        } catch (Exception e) {
            logger.log(WARNING, "Não foi possível carregar o GIF de loading", e);
        }
        
        jBLogin.setEnabled(false);
        
        new Thread(() -> {
            try {
                usuarioDAO.atualizar(validaUsuario, validaUsuario.getUsername());
                Sessao.conectar(validaUsuario);

                JOptionPane.showMessageDialog(this, "Senha atualizada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                jPFSenha.setText("");
                jPFSenha1.setText("");
                new JFTelaEstrutural().setVisible(true);
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar no banco de dados: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                jBLogin.setIcon(null);
                jBLogin.setEnabled(true);
            }
        }).start();

        
    }//GEN-LAST:event_jBLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLogin;
    private javax.swing.JPanel jLCabecalho;
    private javax.swing.JPanel jLPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JPasswordField jPFSenha1;
    // End of variables declaration//GEN-END:variables
}
