/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view.onibus;

import br.com.mycompany.chaponibus.admin.dao.OnibusDAO;
import br.com.mycompany.chaponibus.admin.dao.RotaDAO;
import br.com.mycompany.chaponibus.admin.model.Onibus;
import br.com.mycompany.chaponibus.admin.model.Rota;
import java.awt.Image;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos62347296
 */
public class JDCadastrarOnibus extends javax.swing.JDialog {
    
    private final OnibusDAO onibusDAO;
    private Onibus onibusEmEdicao = null;
    
    private boolean salvouComSucesso = false;

    public JDCadastrarOnibus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        carregarComboBoxRotas();
        
        jLTitulo.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/bus-side-solid.png", 32));
        jLTitulo.setIconTextGap(15);
        
        jBCadastrar.putClientProperty("JButton.buttonType", "borderless");
        jBCancelar.putClientProperty("JButton.buttonType", "borderless");
        
        this.onibusDAO = new OnibusDAO();
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        this.setResizable(false);
        this.setLocationRelativeTo(parent);
    }
    
    public JDCadastrarOnibus(java.awt.Frame parent, boolean modal, Onibus onibus) {
        this(parent, modal); 
        this.onibusEmEdicao = onibus;
        
        jTFPlaca.setText(onibus.getPlaca());
        jTFModelo.setText(onibus.getModelo());
        jSCapacidade.setValue(onibus.getCapacidade());
        
        jCBRota.setSelectedItem(onibus.getRotaAtual());
        
        jTFPlaca.setEditable(false);
        jLTitulo.setText("Editar Ônibus Existente");
        jBCadastrar.setText("Atualizar");
    }
    
    public boolean isSalvouComSucesso() {
        return salvouComSucesso;
    }
    
    public ImageIcon createIcon(String endereco, int tamanho) {
        ImageIcon iconeOriginal = new ImageIcon(getClass().getResource(endereco));
        Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(tamanho, tamanho, Image.SCALE_SMOOTH);
        ImageIcon iconeUsuario = new ImageIcon(imagemRedimensionada);
        return iconeUsuario;
    }
    
    private void carregarComboBoxRotas() {
        RotaDAO rotaDAO = new RotaDAO();
        try {
            List<Rota> listaDasRotas = rotaDAO.listarTodas(); 
            DefaultComboBoxModel<Rota> model = new DefaultComboBoxModel<>();

            for (Rota r : listaDasRotas) {
                model.addElement(r);
            }
            jCBRota.setModel(model);
            jCBRota.setSelectedIndex(-1);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao carregar as rotas do banco de dados:\n" + ex.getMessage(), 
                "Erro de Conexão", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCabecalho = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPPrincipal = new javax.swing.JPanel();
        jLUsuario = new javax.swing.JLabel();
        jLPerfil = new javax.swing.JLabel();
        jTFPlaca = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jTFModelo = new javax.swing.JTextField();
        jLPerfil1 = new javax.swing.JLabel();
        jLPerfil2 = new javax.swing.JLabel();
        jCBRota = new javax.swing.JComboBox<>();
        jSCapacidade = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPCabecalho.setBackground(new java.awt.Color(21, 80, 150));
        jPCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLTitulo.setText("Cadastro de Novo Ônibus");
        jPCabecalho.add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Preencha as informações para adicionar um novo veículo à frota.");
        jPCabecalho.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 430, -1));

        getContentPane().add(jPCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 90));

        jPPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLUsuario.setText("Modelo");
        jPPrincipal.add(jLUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLPerfil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLPerfil.setText("Capacidade");
        jPPrincipal.add(jLPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));
        jPPrincipal.add(jTFPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 40));

        jBCadastrar.setBackground(new java.awt.Color(248, 158, 49));
        jBCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jBCadastrar.setText("Salvar Ônibus");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });
        jPPrincipal.add(jBCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 430, 50));

        jBCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPPrincipal.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 430, 50));
        jPPrincipal.add(jTFModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 450, 40));

        jLPerfil1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLPerfil1.setText("Atribuir Rota");
        jPPrincipal.add(jLPerfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLPerfil2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLPerfil2.setText("Placa");
        jPPrincipal.add(jLPerfil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jPPrincipal.add(jCBRota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 450, 40));

        jSCapacidade.setModel(new javax.swing.SpinnerNumberModel());
        jPPrincipal.add(jSCapacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 200, 40));

        getContentPane().add(jPPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 510, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        String placa = jTFPlaca.getText().trim();
        String modelo = jTFModelo.getText().trim();
        int capacidade = (int) jSCapacidade.getValue();
        Rota rotaSelecionada = (Rota) jCBRota.getSelectedItem(); 

        if (placa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite uma placa válida", "Aviso", JOptionPane.WARNING_MESSAGE);
            jTFPlaca.requestFocus();
            return;
        }
        
        if (modelo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um modelo válido", "Aviso", JOptionPane.WARNING_MESSAGE);
            jTFModelo.requestFocus();
            return;
        }
        
        if (capacidade <= 0) {
            JOptionPane.showMessageDialog(this, "Digite uma capacidade válida", "Aviso", JOptionPane.WARNING_MESSAGE);
            jSCapacidade.requestFocus();
            return;
        }
        
        if (onibusEmEdicao == null) {
            Onibus novoOnibus = new Onibus();
            novoOnibus.setPlaca(placa);
            novoOnibus.setModelo(modelo);
            novoOnibus.setCapacidade(capacidade);
            novoOnibus.setRotaAtual(rotaSelecionada);

            if (onibusDAO.salvar(novoOnibus)) {
                JOptionPane.showMessageDialog(this, "Ônibus cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.salvouComSucesso = true;
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar ônibus. Verifique os dados ou o console.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            onibusEmEdicao.setModelo(modelo);
            onibusEmEdicao.setCapacidade(capacidade);
            onibusEmEdicao.setRotaAtual(rotaSelecionada);

            if (onibusDAO.atualizar(onibusEmEdicao)) {
                JOptionPane.showMessageDialog(this, "Ônibus atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.salvouComSucesso = true;
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar ônibus. Verifique os dados ou o console.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        jTFPlaca.setText("");
        jTFModelo.setText("");
        jCBRota.setSelectedItem(-1);
        jSCapacidade.setValue(0);
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(JDCadastrarOnibus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            JDCadastrarOnibus dialog = new JDCadastrarOnibus(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    // Corrigido: Apenas fecha o Dialog no teste individual, sem matar o sistema principal
                    dialog.dispose(); 
                }
            });
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox<br.com.mycompany.chaponibus.admin.model.Rota> jCBRota;
    private javax.swing.JLabel jLPerfil;
    private javax.swing.JLabel jLPerfil1;
    private javax.swing.JLabel jLPerfil2;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPCabecalho;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JSpinner jSCapacidade;
    private javax.swing.JTextField jTFModelo;
    private javax.swing.JTextField jTFPlaca;
    // End of variables declaration//GEN-END:variables
}
