/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view.onibus;

import br.com.mycompany.chaponibus.admin.dao.OnibusDAO;
import br.com.mycompany.chaponibus.admin.model.Onibus;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Window;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author carlos62347296
 */
public class JPOnibus extends javax.swing.JPanel {
    
    private final OnibusDAO onibusDAO;
    
    int ultimaLinhaSelecionada = -1; 

    /**
     * Creates new form JPCadastroDeUsuario
     */
    
        public JPOnibus() {
        initComponents();
        
        this.onibusDAO = new OnibusDAO();
        
        preencherTabela();
        
        jBExcluir.setVisible(false);
        jBEditar.setVisible(false);
        
        jBEditar.setToolTipText("Editar ônibus selecionado");
        jBExcluir.setToolTipText("Excluir ônibus selecionado");
        
        int iconSize = 20;
        
        jBEditar.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/edit_icon.png", iconSize));
        jBExcluir.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/excluir_icon.png", iconSize));
        
        jTOnibus.setRowHeight(30);
        jTOnibus.setShowHorizontalLines(true);
        jTOnibus.setShowVerticalLines(false);
        jTOnibus.setGridColor(new Color(230, 235, 240));
        jTOnibus.putClientProperty("FlatLaf.style", "showCellFocusIndicator: false");
        
        jTOnibus.getTableHeader().setPreferredSize(new Dimension(0, 45));
        jTOnibus.getTableHeader().putClientProperty("FlatLaf.style", 
                "background: #f1f3f5;" +
                "foreground: #212529;" +
                "font: bold 16;" +
                "separatorColor: #f1f3f5"
        );
    }
    
    public void preencherTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTOnibus.getModel();
        modelo.setNumRows(0);
        
        try {
            List<Onibus> lista = onibusDAO.listarTodos();
        
            for (Onibus o : lista) {
                String nomeRota = (o.getRotaAtual() != null) ? o.getRotaAtual().getNomeRota() : "Nenhuma";

                modelo.addRow(new Object[] {
                    o.getIdOnibus(),
                    o.getPlaca(),
                    o.getModelo(),
                    o.getCapacidade(),
                    nomeRota
                });
            }
            
            jTOnibus.getColumnModel().getColumn(0).setMinWidth(0);
            jTOnibus.getColumnModel().getColumn(0).setMaxWidth(0);
            jTOnibus.getColumnModel().getColumn(0).setWidth(0);
            
            jBExcluir.setVisible(false);
            jBEditar.setVisible(false);
            jTOnibus.clearSelection();
            this.ultimaLinhaSelecionada = -1;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public ImageIcon createIcon(String endereco, int tamanho) {
        ImageIcon iconeOriginal = new ImageIcon(getClass().getResource(endereco));
        Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(tamanho, tamanho, Image.SCALE_SMOOTH);
        ImageIcon iconeUsuario = new ImageIcon(imagemRedimensionada);
        return iconeUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCabecalho = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPPrincipal = new javax.swing.JPanel();
        jBEditar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTOnibus = new javax.swing.JTable();
        jBCadastrarOnibus = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPCabecalho.setBackground(new java.awt.Color(255, 255, 255));
        jPCabecalho.setPreferredSize(new java.awt.Dimension(1110, 80));
        jPCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 80, 150));
        jLabel2.setText("Gestão de Ônibus");
        jPCabecalho.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, -1));

        add(jPCabecalho, java.awt.BorderLayout.PAGE_START);

        jPPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jBEditar.setBackground(new java.awt.Color(208, 125, 7));
        jBEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        jBExcluir.setBackground(new java.awt.Color(204, 0, 0));
        jBExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jTOnibus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Placa", "Modelo", "Capacidade", "Rota"
            }
        ));
        jTOnibus.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTOnibus.getTableHeader().setReorderingAllowed(false);
        // Alinha o redimensionamento automático
        jTOnibus.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        // Coluna 1 (Papel) terá um tamanho fixo e controlado
        jTOnibus.getColumnModel().getColumn(1).setPreferredWidth(150);

        // Coluna 0 (Usuario) vai engolir todo o resto do espaço da tabela automaticamente
        jTOnibus.getColumnModel().getColumn(0).setPreferredWidth(300);

        // Impede o usuário de arrastar e reordenar as colunas de lugar (ex: puxar "Papel" para antes de "Usuario")
        jTOnibus.getTableHeader().setReorderingAllowed(false);

        // Impede o usuário de mudar a largura das colunas arrastando com o mouse
        jTOnibus.getTableHeader().setResizingAllowed(false);
        jTOnibus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTOnibusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTOnibus);
        if (jTOnibus.getColumnModel().getColumnCount() > 0) {
            jTOnibus.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTOnibus.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTOnibus.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTOnibus.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        jBCadastrarOnibus.setBackground(new java.awt.Color(21, 80, 150));
        jBCadastrarOnibus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBCadastrarOnibus.setForeground(new java.awt.Color(255, 255, 255));
        jBCadastrarOnibus.setText("Novo Ônibus");
        jBCadastrarOnibus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCadastrarOnibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarOnibusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPPrincipalLayout = new javax.swing.GroupLayout(jPPrincipal);
        jPPrincipal.setLayout(jPPrincipalLayout);
        jPPrincipalLayout.setHorizontalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPrincipalLayout.createSequentialGroup()
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCadastrarOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPPrincipalLayout.setVerticalGroup(
            jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCadastrarOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        add(jPPrincipal, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarOnibusActionPerformed
        Window janelaMae = SwingUtilities.getWindowAncestor(this);
        
        Frame framePai = (janelaMae instanceof Frame) ? (Frame) janelaMae : null;
        
        JDCadastrarOnibus telaCadastrarOnibus = new JDCadastrarOnibus(framePai, true);
        
        telaCadastrarOnibus.setLocationRelativeTo(janelaMae);
        telaCadastrarOnibus.setVisible(true);
        
        if (telaCadastrarOnibus.isSalvouComSucesso()) {
            preencherTabela();
        }
    }//GEN-LAST:event_jBCadastrarOnibusActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int linha = jTOnibus.getSelectedRow();
        if (linha != -1) {
            String placa = jTOnibus.getValueAt(linha, 1).toString();
            int id = Integer.parseInt(jTOnibus.getValueAt(linha, 0).toString());
            
            int confirmacao = JOptionPane.showConfirmDialog(this, 
                    "Deseja realmente excluir o ônibus de placa " + placa + "?",
                    "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);
            
            if (confirmacao == JOptionPane.YES_OPTION) {
                try {
                    if (onibusDAO.excluir(id)) {
                        JOptionPane.showMessageDialog(this, "Ônibus excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                        preencherTabela();
                    } else {
                        JOptionPane.showMessageDialog(this, "Não foi possível excluir o ônibus. Ele pode não existir mais ou estar vinculado a uma rota ativa.", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir ônibus: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTOnibusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTOnibusMouseClicked
        int linha = jTOnibus.getSelectedRow();
        
        if (linha == -1) {
            jBExcluir.setVisible(false);
            jBEditar.setVisible(false);
            ultimaLinhaSelecionada = -1;
            return;
        }
        
        if (evt.getClickCount() == 2) {
            jBEditarActionPerformed(null);
            return;
        }
        
        if (linha == ultimaLinhaSelecionada) {
            jBExcluir.setVisible(false);
            jBEditar.setVisible(false);
            jTOnibus.clearSelection(); 
            ultimaLinhaSelecionada = -1;
        } else {
            jBExcluir.setVisible(true);
            jBEditar.setVisible(true);
            ultimaLinhaSelecionada = linha;
        }
    }//GEN-LAST:event_jTOnibusMouseClicked

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        int linha = jTOnibus.getSelectedRow();
        
        if (linha != -1) {
            int id = Integer.parseInt(jTOnibus.getValueAt(linha, 0).toString());
            
            Onibus onibus = onibusDAO.procurarOnibus(id);
            
            if (onibus != null) {
                Window janelaMae = SwingUtilities.getWindowAncestor(this);
                Frame framePai = (janelaMae instanceof Frame) ? (Frame) janelaMae : null;

                JDCadastrarOnibus telaEditarOnibus = new JDCadastrarOnibus(framePai, true, onibus);
                telaEditarOnibus.setLocationRelativeTo(janelaMae);
                telaEditarOnibus.setVisible(true);

                if (telaEditarOnibus.isSalvouComSucesso()) {
                    preencherTabela();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro: Nenhum ônibus encontrado ou selecionado", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarOnibus;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPCabecalho;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTOnibus;
    // End of variables declaration//GEN-END:variables
}
