/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view;

import br.com.mycompany.chaponibus.admin.dao.UsuarioDAO;
import br.com.mycompany.chaponibus.admin.model.Sessao;
import br.com.mycompany.chaponibus.admin.model.Usuario;
import static java.awt.EventQueue.invokeLater;
import java.awt.Image;
import java.net.URL;
import static java.util.logging.Level.WARNING;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ce498
 */
public class JFLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFLogin.class.getName());
    private final UsuarioDAO usuarioDAO;
    private boolean senhaVisivel = false;

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ChapÔnibus - Login");
        this.usuarioDAO = new UsuarioDAO();
        Usuario teste = new Usuario("teste", "1111", "admin");
        usuarioDAO.salvar(teste);
        jTFUsuario.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLUsuario = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jLSenha = new javax.swing.JLabel();
        jBLogin = new javax.swing.JButton();
        jPFSenha = new javax.swing.JPasswordField();
        jBVerSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        jLUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLUsuario.setText("Usuário:");

        jTFUsuario.addActionListener(this::jTFUsuarioActionPerformed);

        jLSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLSenha.setText("Senha:");

        jBLogin.setText("Login");
        jBLogin.addActionListener(this::jBLoginActionPerformed);

        jPFSenha.addActionListener(this::jPFSenhaActionPerformed);

        jBVerSenha.setText("Mostrar");
        jBVerSenha.addActionListener(this::jBVerSenhaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLUsuario)
                            .addComponent(jLSenha))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBVerSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFUsuario))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUsuario)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPFSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jBVerSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLSenha))
                .addGap(18, 18, 18)
                .addComponent(jBLogin)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginActionPerformed
        efetuarLogin();
    }//GEN-LAST:event_jBLoginActionPerformed

    private void jBVerSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerSenhaActionPerformed
        if (!senhaVisivel) {
            jPFSenha.setEchoChar((char) 0);
            jBVerSenha.setText("Ocultar");
            senhaVisivel = true;
        } else {
            jPFSenha.setEchoChar('•');
            jBVerSenha.setText("Mostrar");
            senhaVisivel = false;
        }
        
        jPFSenha.requestFocus();
    }//GEN-LAST:event_jBVerSenhaActionPerformed

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuarioActionPerformed
        efetuarLogin();
    }//GEN-LAST:event_jTFUsuarioActionPerformed

    private void jPFSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFSenhaActionPerformed
        efetuarLogin();
    }//GEN-LAST:event_jPFSenhaActionPerformed
    
    private void efetuarLogin() {
        if (jTFUsuario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira um usuário");
            jTFUsuario.requestFocus();
            return;
        }
        
        String senha = new String(jPFSenha.getPassword());
        
        if (senha.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira uma senha");
            jPFSenha.requestFocus();
            return;
        }
        
        jBLogin.setEnabled(false);
        jBLogin.setText("");
        
        try {
            URL imgURL = getClass().getResource("/br/com/mycompany/chaponibus/admin/assets/loading.gif");
            if (imgURL != null) {
                ImageIcon iconeOriginal = new ImageIcon(imgURL);
                Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(16, 16, Image.SCALE_DEFAULT);
                jBLogin.setIcon(new ImageIcon(imagemRedimensionada));
            } else {
                jBLogin.setText("Carregando...");
            }
        } catch (Exception e) {
            logger.log(WARNING, "Não foi possível carregar o GIF de loading", e);
        }
        
        new Thread(() -> {
            Usuario validaUsuario = usuarioDAO.validarLogin(jTFUsuario.getText(), senha);
            
            invokeLater(() -> {
                if (validaUsuario != null) {
                    Sessao.conectar(validaUsuario);
                    
                    JOptionPane.showMessageDialog(null, "Bem-vindo, " + validaUsuario.getUsername() + "!");
                    jBLogin.setIcon(null);
                    
                    new JFTelaInicial().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Informe um usuário e senha válidos");
                    
                    jBLogin.setIcon(null);
                    jBLogin.setEnabled(true);
                    jBLogin.setText("Login");
                    
                    jPFSenha.setText("");
                    jPFSenha.requestFocus();
                }
            });
        }).start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLogin;
    private javax.swing.JButton jBVerSenha;
    private javax.swing.JLabel jLSenha;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
