/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view;

import br.com.mycompany.chaponibus.admin.model.Sessao;
import br.com.mycompany.chaponibus.admin.model.Usuario;
import java.awt.CardLayout;
import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author ce498
 */
public class JFTelaEstrutural extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFTelaEstrutural.class.getName());
    private Usuario atual;

    /**
     * Creates new form JFTelaInicial
     */
    public JFTelaEstrutural() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.atual = Sessao.getUsuarioLogado();
        
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardInicial");
        
        if (atual == null || !"Super Administrador".equalsIgnoreCase(atual.getRole())) {
            jBNavCadastro1.setVisible(false);
        }
        
        
        // altera a cor da borda (no caso deixa sem, nesse caso)
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.GRAY));
        jBNavCadastro1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.GRAY));
        jBRotas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.GRAY));
        jBUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.GRAY));
        jBBairros.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.GRAY));
        jBOnibus.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, java.awt.Color.GRAY));
        
        int iconSize = 20; //variavel do tamanho dos icones
        
        //adicionar icone ao botao ou outro item
        jButton1.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/home_icon.png", iconSize));
        //adicionar espaço entre o icone e texto
        jButton1.setIconTextGap(10);
        
        jBNavCadastro1.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/usuarios_icon.png", iconSize));
        jBNavCadastro1.setIconTextGap(10);
        
        jBRotas.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/rotas_icon.png", iconSize));
        jBRotas.setIconTextGap(10);
        
        jBBairros.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/map_icon.png", iconSize));
        jBBairros.setIconTextGap(10);
        
        jBUsuario.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/usuario.png", iconSize));
        jBUsuario.setIconTextGap(10);
        
        jBOnibus.setIcon(createIcon("/br/com/mycompany/chaponibus/admin/assets/bus_icon.png", iconSize));
        jBOnibus.setIconTextGap(10);
    }
    
    public ImageIcon createIcon(String endereco, int tamanho) {
        ImageIcon iconeOriginal = new ImageIcon(getClass().getResource(endereco));
        Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(tamanho, tamanho, Image.SCALE_SMOOTH);
        ImageIcon iconeUsuario = new ImageIcon(imagemRedimensionada);
        return iconeUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPainelNav = new javax.swing.JPanel();
        jBNavCadastro1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBRotas = new javax.swing.JButton();
        jBUsuario = new javax.swing.JButton();
        jBBairros = new javax.swing.JButton();
        jLLogo = new javax.swing.JLabel();
        jLLogo1 = new javax.swing.JLabel();
        jBOnibus = new javax.swing.JButton();
        jPPainelConteudo = new javax.swing.JPanel();
        jPTelaInicial = new br.com.mycompany.chaponibus.admin.view.JPTelaInicial();
        jPUsuarios1 = new br.com.mycompany.chaponibus.admin.view.JPUsuarios();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPPainelNav.setBackground(new java.awt.Color(238, 241, 243));
        jPPainelNav.setMinimumSize(new java.awt.Dimension(170, 160));
        jPPainelNav.setPreferredSize(new java.awt.Dimension(170, 160));
        jPPainelNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBNavCadastro1.setBackground(new java.awt.Color(238, 241, 243));
        jBNavCadastro1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBNavCadastro1.setForeground(new java.awt.Color(21, 80, 150));
        jBNavCadastro1.setText("Usuários");
        jBNavCadastro1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBNavCadastro1.addActionListener(this::jBNavCadastro1ActionPerformed);
        jPPainelNav.add(jBNavCadastro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, 40));

        jButton1.setBackground(new java.awt.Color(238, 241, 243));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(21, 80, 150));
        jButton1.setText("Home");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPPainelNav.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 40));

        jBRotas.setBackground(new java.awt.Color(238, 241, 243));
        jBRotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBRotas.setForeground(new java.awt.Color(21, 80, 150));
        jBRotas.setText("Rotas");
        jBRotas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPPainelNav.add(jBRotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 40));

        jBUsuario.setBackground(new java.awt.Color(238, 241, 243));
        jBUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBUsuario.setForeground(new java.awt.Color(24, 28, 30));
        jBUsuario.setText("NomeUsuario");
        jBUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBUsuario.addActionListener(this::jBUsuarioActionPerformed);
        jPPainelNav.add(jBUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 130, 40));

        jBBairros.setBackground(new java.awt.Color(238, 241, 243));
        jBBairros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBBairros.setForeground(new java.awt.Color(21, 80, 150));
        jBBairros.setText("Bairros");
        jBBairros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBBairros.addActionListener(this::jBBairrosActionPerformed);
        jPPainelNav.add(jBBairros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 40));

        jLLogo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLLogo.setForeground(new java.awt.Color(91, 95, 97));
        jLLogo.setText("Painel Administrativo");
        jPPainelNav.add(jLLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 70));

        jLLogo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLLogo1.setForeground(new java.awt.Color(0, 48, 99));
        jLLogo1.setText("Chapônibus");
        jPPainelNav.add(jLLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 70));

        jBOnibus.setBackground(new java.awt.Color(238, 241, 243));
        jBOnibus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBOnibus.setForeground(new java.awt.Color(21, 80, 150));
        jBOnibus.setText("Ônibus");
        jBOnibus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBOnibus.addActionListener(this::jBOnibusActionPerformed);
        jPPainelNav.add(jBOnibus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 40));

        getContentPane().add(jPPainelNav, java.awt.BorderLayout.LINE_START);

        jPPainelConteudo.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPTelaInicialLayout = new javax.swing.GroupLayout(jPTelaInicial);
        jPTelaInicial.setLayout(jPTelaInicialLayout);
        jPTelaInicialLayout.setHorizontalGroup(
            jPTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        jPTelaInicialLayout.setVerticalGroup(
            jPTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPPainelConteudo.add(jPTelaInicial, "cardInicial");
        jPPainelConteudo.add(jPUsuarios1, "cardUsuarios");

        getContentPane().add(jPPainelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNavCadastro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNavCadastro1ActionPerformed
//        jPCadastroDeUsuario1.preencherTabela();
        
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardUsuarios");
    }//GEN-LAST:event_jBNavCadastro1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardInicial");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBUsuarioActionPerformed

    private void jBBairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBairrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBairrosActionPerformed

    private void jBOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOnibusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBOnibusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFTelaEstrutural().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBairros;
    private javax.swing.JButton jBNavCadastro1;
    private javax.swing.JButton jBOnibus;
    private javax.swing.JButton jBRotas;
    private javax.swing.JButton jBUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLLogo1;
    private javax.swing.JPanel jPPainelConteudo;
    private javax.swing.JPanel jPPainelNav;
    private br.com.mycompany.chaponibus.admin.view.JPTelaInicial jPTelaInicial;
    private br.com.mycompany.chaponibus.admin.view.JPUsuarios jPUsuarios1;
    // End of variables declaration//GEN-END:variables
}
