/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view;

import br.com.mycompany.chaponibus.admin.util.Sessao;
import br.com.mycompany.chaponibus.admin.model.Usuario;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author ce498
 */
public class JFTelaEstrutural extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFTelaEstrutural.class.getName());
    private Usuario atual;

    /**
     * Creates new form JFTelaInicial
     */
    public JFTelaEstrutural() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.atual = Sessao.getUsuarioLogado();
        
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardInicial");
        
        if (atual == null || !"Super Administrador".equalsIgnoreCase(atual.getRole())) {
            jBUsuarios.setVisible(false);
        }
        
        jBUsuario.setText(Sessao.getUsuarioLogado().getUsername());
        
        configurarBotaoNav(jBHome, "/br/com/mycompany/chaponibus/admin/assets/home_icon.png", "Home");
        configurarBotaoNav(jBRotas, "/br/com/mycompany/chaponibus/admin/assets/rotas_icon.png", "Rotas");
        configurarBotaoNav(jBOnibus, "/br/com/mycompany/chaponibus/admin/assets/bus_icon.png", "Ônibus");
        configurarBotaoNav(jBBairros, "/br/com/mycompany/chaponibus/admin/assets/map_icon.png", "Bairros");
        configurarBotaoNav(jBUsuarios, "/br/com/mycompany/chaponibus/admin/assets/usuarios_icon.png", "Usuários");
        configurarBotaoNav(jBUsuario, "/br/com/mycompany/chaponibus/admin/assets/usuario.png", Sessao.getUsuarioLogado().getUsername());
    }
    
    private void configurarBotaoNav(javax.swing.JButton btn, String iconPath, String texto) {
        btn.putClientProperty("JButton.buttonType", "borderless");
        btn.setFocusPainted(false);
        btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn.setIconTextGap(15);

        btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));

        btn.setIcon(createIcon(iconPath, 20));
    }
    
    public ImageIcon createIcon(String endereco, int tamanho) {
        ImageIcon iconeOriginal = new ImageIcon(getClass().getResource(endereco));
        Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(tamanho, tamanho, Image.SCALE_SMOOTH);
        ImageIcon iconeUsuario = new ImageIcon(imagemRedimensionada);
        return iconeUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPainelNav = new javax.swing.JPanel();
        jPCabecalho = new javax.swing.JPanel();
        jBUsuarios = new javax.swing.JButton();
        jBHome = new javax.swing.JButton();
        jBRotas = new javax.swing.JButton();
        jBUsuario = new javax.swing.JButton();
        jBBairros = new javax.swing.JButton();
        jLLogo = new javax.swing.JLabel();
        jLLogo1 = new javax.swing.JLabel();
        jPBotoes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jBRotas = new javax.swing.JButton();
        jBOnibus = new javax.swing.JButton();
        jBNavCadastro1 = new javax.swing.JButton();
        jPRodape = new javax.swing.JPanel();
        jBUsuario = new javax.swing.JButton();
        jPPainelConteudo = new javax.swing.JPanel();
        jPTelaInicial = new br.com.mycompany.chaponibus.admin.view.JPTelaInicial();
        jPRotas = new br.com.mycompany.chaponibus.admin.view.rotas.JPRotas();
        jPUsuarios1 = new br.com.mycompany.chaponibus.admin.view.usuarios.JPUsuarios();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPPainelNav.setBackground(new java.awt.Color(244, 247, 249));
        jPPainelNav.setMinimumSize(new java.awt.Dimension(180, 160));
        jPPainelNav.setPreferredSize(new java.awt.Dimension(180, 160));
        jPPainelNav.setLayout(new java.awt.BorderLayout());

        jPCabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLLogo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLLogo.setForeground(new java.awt.Color(91, 95, 97));
        jLLogo.setText("Painel Administrativo");
        jPCabecalho.add(jLLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 70));

        jLLogo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLLogo1.setForeground(new java.awt.Color(0, 48, 99));
        jLLogo1.setText("Chapônibus");
        jPCabecalho.add(jLLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 70));

        jPPainelNav.add(jPCabecalho, java.awt.BorderLayout.NORTH);

        jPBotoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(238, 241, 243));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(21, 80, 150));
        jButton1.setText("Home");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPBotoes.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 40));

        jBRotas.setBackground(new java.awt.Color(238, 241, 243));
        jBRotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBRotas.setForeground(new java.awt.Color(21, 80, 150));
        jBRotas.setText("Rotas");
        jBRotas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBRotas.addActionListener(this::jBRotasActionPerformed);
        jPBotoes.add(jBRotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 40));

        jBOnibus.setBackground(new java.awt.Color(238, 241, 243));
        jBOnibus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBOnibus.setForeground(new java.awt.Color(21, 80, 150));
        jBOnibus.setText("Ônibus");
        jBOnibus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBOnibus.addActionListener(this::jBOnibusActionPerformed);
        jPBotoes.add(jBOnibus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 40));

        jBNavCadastro1.setBackground(new java.awt.Color(238, 241, 243));
        jBNavCadastro1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBNavCadastro1.setForeground(new java.awt.Color(21, 80, 150));
        jBNavCadastro1.setText("Usuários");
        jBNavCadastro1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBNavCadastro1.addActionListener(this::jBNavCadastro1ActionPerformed);
        jPBotoes.add(jBNavCadastro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 40));

        jPPainelNav.add(jPBotoes, java.awt.BorderLayout.CENTER);

        jBUsuario.setBackground(new java.awt.Color(244, 247, 249));
        jBUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBUsuario.setForeground(new java.awt.Color(24, 28, 30));
        jBUsuario.setText("NomeUsuario");
        jBUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBUsuario.addActionListener(this::jBUsuarioActionPerformed);
        jPPainelNav.add(jBUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 130, 40));

        jBBairros.setBackground(new java.awt.Color(244, 247, 249));
        jBBairros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBBairros.setForeground(new java.awt.Color(21, 80, 150));
        jBBairros.setText("Bairros");
        jBBairros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBBairros.addActionListener(this::jBBairrosActionPerformed);
        jPPainelNav.add(jBBairros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 40));

        javax.swing.GroupLayout jPRodapeLayout = new javax.swing.GroupLayout(jPRodape);
        jPRodape.setLayout(jPRodapeLayout);
        jPRodapeLayout.setHorizontalGroup(
            jPRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(jPRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPRodapeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPRodapeLayout.setVerticalGroup(
            jPRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(jPRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPRodapeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPPainelNav.add(jPRodape, java.awt.BorderLayout.SOUTH);
        jBOnibus.setBackground(new java.awt.Color(244, 247, 249));
        jBOnibus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBOnibus.setForeground(new java.awt.Color(21, 80, 150));
        jBOnibus.setText("Ônibus");
        jBOnibus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBOnibus.addActionListener(this::jBOnibusActionPerformed);
        jPPainelNav.add(jBOnibus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 40));

        getContentPane().add(jPPainelNav, java.awt.BorderLayout.LINE_START);

        jPPainelConteudo.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPTelaInicialLayout = new javax.swing.GroupLayout(jPTelaInicial);
        jPTelaInicial.setLayout(jPTelaInicialLayout);
        jPTelaInicialLayout.setHorizontalGroup(
            jPTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jPTelaInicialLayout.setVerticalGroup(
            jPTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPPainelConteudo.add(jPTelaInicial, "cardInicial");
        jPPainelConteudo.add(jPRotas, "cardRotas");
        jPPainelConteudo.add(jPUsuarios1, "cardUsuarios");

        getContentPane().add(jPPainelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUsuariosActionPerformed
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardUsuarios");
    }//GEN-LAST:event_jBUsuariosActionPerformed

    private void jBHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHomeActionPerformed
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardInicial");
    }//GEN-LAST:event_jBHomeActionPerformed

    private void jBUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBUsuarioActionPerformed

    private void jBOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOnibusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBOnibusActionPerformed

    private void jBRotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRotasActionPerformed
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardRotas");
    }//GEN-LAST:event_jBRotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new JFTelaEstrutural().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBNavCadastro1;
    private javax.swing.JButton jBBairros;
    private javax.swing.JButton jBHome;
    private javax.swing.JButton jBOnibus;
    private javax.swing.JButton jBRotas;
    private javax.swing.JButton jBUsuario;
    private javax.swing.JButton jBUsuarios;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLLogo1;
    private javax.swing.JPanel jPBotoes;
    private javax.swing.JPanel jPCabecalho;
    private javax.swing.JPanel jPPainelConteudo;
    private javax.swing.JPanel jPPainelNav;
    private javax.swing.JPanel jPRodape;
    private br.com.mycompany.chaponibus.admin.view.rotas.JPRotas jPRotas;
    private br.com.mycompany.chaponibus.admin.view.JPTelaInicial jPTelaInicial;
    private br.com.mycompany.chaponibus.admin.view.usuarios.JPUsuarios jPUsuarios1;
    // End of variables declaration//GEN-END:variables
}
