/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view;

import br.com.mycompany.chaponibus.admin.util.Sessao;
import br.com.mycompany.chaponibus.admin.model.Usuario;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author ce498
 */
public class JFTelaEstrutural extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFTelaEstrutural.class.getName());
    private Usuario atual;

    /**
     * Creates new form JFTelaInicial
     */
    public JFTelaEstrutural() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.atual = Sessao.getUsuarioLogado();
        
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardInicial");
        
        if (atual == null || !"Super Administrador".equalsIgnoreCase(atual.getRole())) {
            jBUsuarios.setVisible(false);
        }
        
        jBUsuario.setText(Sessao.getUsuarioLogado().getUsername());
        
        configurarBotaoNav(jBHome, "/br/com/mycompany/chaponibus/admin/assets/home_icon.png", "Home");
        configurarBotaoNav(jBRotas, "/br/com/mycompany/chaponibus/admin/assets/rotas_icon.png", "Rotas");
        configurarBotaoNav(jBOnibus, "/br/com/mycompany/chaponibus/admin/assets/bus_icon.png", "Ônibus");
        configurarBotaoNav(jBUsuarios, "/br/com/mycompany/chaponibus/admin/assets/usuarios_icon.png", "Usuários");
        configurarBotaoNav(jBUsuario, "/br/com/mycompany/chaponibus/admin/assets/usuario.png", Sessao.getUsuarioLogado().getUsername());
    }
    
    private void configurarBotaoNav(javax.swing.JButton btn, String iconPath, String texto) {
        btn.putClientProperty("JButton.buttonType", "borderless");
        btn.setFocusPainted(false);
        btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn.setIconTextGap(15);

        btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15));

        btn.setIcon(createIcon(iconPath, 20));
    }
    
    public ImageIcon createIcon(String endereco, int tamanho) {
        ImageIcon iconeOriginal = new ImageIcon(getClass().getResource(endereco));
        Image imagemRedimensionada = iconeOriginal.getImage().getScaledInstance(tamanho, tamanho, Image.SCALE_SMOOTH);
        ImageIcon iconeUsuario = new ImageIcon(imagemRedimensionada);
        return iconeUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPainelNav = new javax.swing.JPanel();
        jPCabecalho = new javax.swing.JPanel();
        jLLogo = new javax.swing.JLabel();
        jLLogo1 = new javax.swing.JLabel();
        jPBotoes = new javax.swing.JPanel();
        jBUsuarios = new javax.swing.JButton();
        jBHome = new javax.swing.JButton();
        jBRotas = new javax.swing.JButton();
        jBOnibus = new javax.swing.JButton();
        jPRodape = new javax.swing.JPanel();
        jBUsuario = new javax.swing.JButton();
        jPPainelConteudo = new javax.swing.JPanel();
        jPTelaInicial = new br.com.mycompany.chaponibus.admin.view.JPTelaInicial();
        jPRotas = new br.com.mycompany.chaponibus.admin.view.rotas.JPRotas();
        jPUsuarios1 = new br.com.mycompany.chaponibus.admin.view.usuarios.JPUsuarios();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 247, 249));

        jPPainelNav.setBackground(new java.awt.Color(244, 247, 249));
        jPPainelNav.setMinimumSize(new java.awt.Dimension(180, 160));
        jPPainelNav.setOpaque(false);
        jPPainelNav.setPreferredSize(new java.awt.Dimension(180, 160));
        jPPainelNav.setLayout(new java.awt.BorderLayout());

        jPCabecalho.setBackground(new java.awt.Color(244, 247, 249));

        jLLogo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLLogo.setForeground(new java.awt.Color(91, 95, 97));
        jLLogo.setText("Painel Administrativo");

        jLLogo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLLogo1.setForeground(new java.awt.Color(0, 48, 99));
        jLLogo1.setText("Chapônibus");

        javax.swing.GroupLayout jPCabecalhoLayout = new javax.swing.GroupLayout(jPCabecalho);
        jPCabecalho.setLayout(jPCabecalhoLayout);
        jPCabecalhoLayout.setHorizontalGroup(
            jPCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(jPCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPCabecalhoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPCabecalhoLayout.setVerticalGroup(
            jPCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(jPCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPCabecalhoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLLogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPCabecalhoLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPPainelNav.add(jPCabecalho, java.awt.BorderLayout.PAGE_START);

        jPBotoes.setBackground(new java.awt.Color(244, 247, 249));
        jPBotoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBUsuarios.setBackground(new java.awt.Color(244, 247, 249));
        jBUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBUsuarios.setForeground(new java.awt.Color(21, 80, 150));
        jBUsuarios.setText("Usuários");
        jBUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBUsuarios.addActionListener(this::jBUsuariosActionPerformed);
        jPBotoes.add(jBUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 40));

        jBHome.setBackground(new java.awt.Color(244, 247, 249));
        jBHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBHome.setForeground(new java.awt.Color(21, 80, 150));
        jBHome.setText("Home");
        jBHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBHome.addActionListener(this::jBHomeActionPerformed);
        jPBotoes.add(jBHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 40));

        jBRotas.setBackground(new java.awt.Color(244, 247, 249));
        jBRotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBRotas.setForeground(new java.awt.Color(21, 80, 150));
        jBRotas.setText("Rotas");
        jBRotas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBRotas.addActionListener(this::jBRotasActionPerformed);
        jPBotoes.add(jBRotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 40));

        jBOnibus.setBackground(new java.awt.Color(244, 247, 249));
        jBOnibus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBOnibus.setForeground(new java.awt.Color(21, 80, 150));
        jBOnibus.setText("Ônibus");
        jBOnibus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBOnibus.addActionListener(this::jBOnibusActionPerformed);
        jPBotoes.add(jBOnibus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 40));

        jPPainelNav.add(jPBotoes, java.awt.BorderLayout.CENTER);

        jPRodape.setBackground(new java.awt.Color(244, 247, 249));

        jBUsuario.setBackground(new java.awt.Color(244, 247, 249));
        jBUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBUsuario.setForeground(new java.awt.Color(24, 28, 30));
        jBUsuario.setText("NomeUsuario");
        jBUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBUsuario.addActionListener(this::jBUsuarioActionPerformed);

        javax.swing.GroupLayout jPRodapeLayout = new javax.swing.GroupLayout(jPRodape);
        jPRodape.setLayout(jPRodapeLayout);
        jPRodapeLayout.setHorizontalGroup(
            jPRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRodapeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPRodapeLayout.setVerticalGroup(
            jPRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRodapeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPPainelNav.add(jPRodape, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPPainelNav, java.awt.BorderLayout.LINE_START);

        jPPainelConteudo.setLayout(new java.awt.CardLayout());
        jPPainelConteudo.add(jPTelaInicial, "cardInicial");
        jPPainelConteudo.add(jPRotas, "cardRotas");
        jPPainelConteudo.add(jPUsuarios1, "cardUsuarios");

        getContentPane().add(jPPainelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUsuariosActionPerformed
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardUsuarios");
    }//GEN-LAST:event_jBUsuariosActionPerformed

    private void jBHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHomeActionPerformed
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardInicial");
    }//GEN-LAST:event_jBHomeActionPerformed

    private void jBUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBUsuarioActionPerformed

    private void jBOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOnibusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBOnibusActionPerformed

    private void jBRotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRotasActionPerformed
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardRotas");
    }//GEN-LAST:event_jBRotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new JFTelaEstrutural().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBHome;
    private javax.swing.JButton jBOnibus;
    private javax.swing.JButton jBRotas;
    private javax.swing.JButton jBUsuario;
    private javax.swing.JButton jBUsuarios;
    private javax.swing.JLabel jLLogo;
    private javax.swing.JLabel jLLogo1;
    private javax.swing.JPanel jPBotoes;
    private javax.swing.JPanel jPCabecalho;
    private javax.swing.JPanel jPPainelConteudo;
    private javax.swing.JPanel jPPainelNav;
    private javax.swing.JPanel jPRodape;
    private br.com.mycompany.chaponibus.admin.view.rotas.JPRotas jPRotas;
    private br.com.mycompany.chaponibus.admin.view.JPTelaInicial jPTelaInicial;
    private br.com.mycompany.chaponibus.admin.view.usuarios.JPUsuarios jPUsuarios1;
    // End of variables declaration//GEN-END:variables
}
