/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view;

import br.com.mycompany.chaponibus.admin.model.Sessao;
import br.com.mycompany.chaponibus.admin.model.Usuario;
import java.awt.CardLayout;

/**
 *
 * @author ce498
 */
public class JFTelaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFTelaInicial.class.getName());
    private Usuario atual;

    /**
     * Creates new form JFTelaInicial
     */
    public JFTelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.atual = Sessao.getUsuarioLogado();
        
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardTeste");
        
        if (atual == null || !"admin".equalsIgnoreCase(atual.getRole())) {
            jBNavCadastro.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPainelNav = new javax.swing.JPanel();
        jBNavCadastro = new javax.swing.JButton();
        jPPainelConteudo = new javax.swing.JPanel();
        jPCadastroDeUsuario1 = new br.com.mycompany.chaponibus.admin.view.JPCadastroDeUsuario();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBNavCadastro.setText("Tela de cadastro");
        jBNavCadastro.addActionListener(this::jBNavCadastroActionPerformed);

        javax.swing.GroupLayout jPPainelNavLayout = new javax.swing.GroupLayout(jPPainelNav);
        jPPainelNav.setLayout(jPPainelNavLayout);
        jPPainelNavLayout.setHorizontalGroup(
            jPPainelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPainelNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBNavCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPPainelNavLayout.setVerticalGroup(
            jPPainelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPainelNavLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jBNavCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        getContentPane().add(jPPainelNav, java.awt.BorderLayout.LINE_START);

        jPPainelConteudo.setLayout(new java.awt.CardLayout());
        jPPainelConteudo.add(jPCadastroDeUsuario1, "cardUsuarios");

        getContentPane().add(jPPainelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNavCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNavCadastroActionPerformed
        CardLayout cl = (CardLayout) jPPainelConteudo.getLayout();
        cl.show(jPPainelConteudo, "cardUsuarios");
    }//GEN-LAST:event_jBNavCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFTelaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBNavCadastro;
    private br.com.mycompany.chaponibus.admin.view.JPCadastroDeUsuario jPCadastroDeUsuario1;
    private javax.swing.JPanel jPPainelConteudo;
    private javax.swing.JPanel jPPainelNav;
    // End of variables declaration//GEN-END:variables
}
