/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view;

import br.com.mycompany.chaponibus.admin.dao.UsuarioDAO;
import br.com.mycompany.chaponibus.admin.model.Usuario;
import java.awt.Frame;
import java.awt.Window;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlos62347296
 */
public class JPUsuarios extends javax.swing.JPanel {
    
    private final UsuarioDAO usuarioDAO;
    
    int ultimaLinhaSelecionada = -1; 

    /**
     * Creates new form JPCadastroDeUsuario
     */
    public JPUsuarios() {
        initComponents();
        
        this.usuarioDAO = new UsuarioDAO();
        
        preencherTabela();
        
        jBExcluir.setVisible(false);
        jBEditar.setVisible(false);
        
        jBEditar.setToolTipText("Editar usuário selecionado");
        jBExcluir.setToolTipText("Excluir usuário selecionado");
    }
    
    private void preencherTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTUsuarios.getModel();
        
        modelo.setNumRows(0);
        
        try {
            List<Usuario> lista = usuarioDAO.listarTodos();
        
            for (Usuario u : lista) {
                modelo.addRow(new Object[] {
                    u.getUsername(),
                    u.getRole()
                });
            }
            
            jBExcluir.setVisible(false);
            jBEditar.setVisible(false);
            this.ultimaLinhaSelecionada = -1;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBCadastrarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();
        jBExcluir = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();

        jLabel1.setText("USUÁRIOS");

        jBCadastrarUsuario.setText("Cadastrar");
        jBCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarUsuarioActionPerformed(evt);
            }
        });

        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Usuario", "Papel"
            }
        ) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        jTUsuarios.getTableHeader().setReorderingAllowed(false);
        // Alinha o redimensionamento automático
        jTUsuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);

        // Coluna 1 (Papel) terá um tamanho fixo e controlado
        jTUsuarios.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTUsuarios.getColumnModel().getColumn(1).setMaxWidth(200);
        jTUsuarios.getColumnModel().getColumn(1).setMinWidth(100);

        // Coluna 0 (Usuario) vai engolir todo o resto do espaço da tabela automaticamente
        jTUsuarios.getColumnModel().getColumn(0).setPreferredWidth(450);

        // Impede o usuário de arrastar e reordenar as colunas de lugar (ex: puxar "Papel" para antes de "Usuario")
        jTUsuarios.getTableHeader().setReorderingAllowed(false);

        // Impede o usuário de mudar a largura das colunas arrastando com o mouse
        jTUsuarios.getTableHeader().setResizingAllowed(false);
        jTUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTUsuarios);

        jBExcluir.setBackground(new java.awt.Color(204, 0, 0));
        jBExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBExcluir.setText("A");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBEditar.setBackground(new java.awt.Color(0, 0, 153));
        jBEditar.setText("E");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCadastrarUsuario))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrarUsuario)
                    .addComponent(jBExcluir)
                    .addComponent(jBEditar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarUsuarioActionPerformed
        Window janelaMae = SwingUtilities.getWindowAncestor(this);
        
        Frame framePai = (janelaMae instanceof Frame) ? (Frame) janelaMae : null;
        
        JDCadastrarUsuario telaCadastrarUsuario = new JDCadastrarUsuario(framePai, true);
        
        telaCadastrarUsuario.setLocationRelativeTo(janelaMae);
        telaCadastrarUsuario.setVisible(true);
        
        preencherTabela();
    }//GEN-LAST:event_jBCadastrarUsuarioActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int linha = jTUsuarios.getSelectedRow();
        if (linha != -1) {
            String username = jTUsuarios.getValueAt(linha, 0).toString();
            
            int confirmacao = JOptionPane.showConfirmDialog(this, 
                    "Deseja realmente excluir o usuário " + username + "?",
                    "", JOptionPane.YES_NO_OPTION);
            
            if (confirmacao == JOptionPane.YES_OPTION) {
                usuarioDAO.excluir(username);
                preencherTabela();
            }
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsuariosMouseClicked
        int linha = jTUsuarios.getSelectedRow();
        
        if (linha == -1) {
            jBExcluir.setVisible(false);
            jBEditar.setVisible(false);
            ultimaLinhaSelecionada = -1;
            return;
        }
        
        if (linha == ultimaLinhaSelecionada) {
            jBExcluir.setVisible(false);
            jBEditar.setVisible(false);
            jTUsuarios.clearSelection(); 
            ultimaLinhaSelecionada = -1;
        } else {
            jBExcluir.setVisible(true);
            jBEditar.setVisible(true);
            ultimaLinhaSelecionada = linha;
        }
    }//GEN-LAST:event_jTUsuariosMouseClicked

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        int linha = jTUsuarios.getSelectedRow();
        
        if (linha != -1) {
            String username = jTUsuarios.getValueAt(linha, 0).toString();
            
            Usuario usuario = usuarioDAO.procurarUsuario(username);
            
            if (usuario != null) {
                Window janelaMae = SwingUtilities.getWindowAncestor(this);
                Frame framePai = (janelaMae instanceof Frame) ? (Frame) janelaMae : null;

                JDCadastrarUsuario telaEditarUsuario = new JDCadastrarUsuario(framePai, true, usuario);
                telaEditarUsuario.setLocationRelativeTo(janelaMae);
                telaEditarUsuario.setVisible(true);

                preencherTabela();
            } else {
                JOptionPane.showMessageDialog(this, "Erro: Nenhum usuário encontrado ou selecionado", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrarUsuario;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTUsuarios;
    // End of variables declaration//GEN-END:variables
}
