/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view.rotas;

import javax.swing.SwingUtilities;
import java.util.List;
import org.jxmapviewer.viewer.GeoPosition;

/**
 *
 * @author ce498
 */
public class JPDescricaoRotas extends javax.swing.JPanel {

    /**
     * Creates new form JPDescricaoRotas
     */
    public JPDescricaoRotas() {
        initComponents();
        
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21,80,150), 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLNome = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRBPontoRota = new javax.swing.JRadioButton();
        jLCadastrarPontos = new javax.swing.JLabel();
        jRBPontoOnibus = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPontosOnibus = new javax.swing.JTable();
        jBRemoverPonto = new javax.swing.JButton();
        jBConfirmar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 247, 249));
        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(244, 247, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLNome.setText("Nome da rota");
        jPanel1.add(jLNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 360, -1));

        buttonGroup1.add(jRBPontoRota);
        jRBPontoRota.setSelected(true);
        jRBPontoRota.setText("Ponto de Rota");
        jRBPontoRota.addActionListener(this::jRBPontoRotaActionPerformed);
        jPanel1.add(jRBPontoRota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLCadastrarPontos.setText("Cadastrar pontos");
        jPanel1.add(jLCadastrarPontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        buttonGroup1.add(jRBPontoOnibus);
        jRBPontoOnibus.setText("Ponto de Ônibus");
        jRBPontoOnibus.setActionCommand("");
        jRBPontoOnibus.addActionListener(this::jRBPontoOnibusActionPerformed);
        jPanel1.add(jRBPontoOnibus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jTPontosOnibus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Pontos de Ônibus Cadastrados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTPontosOnibus);
        if (jTPontosOnibus.getColumnModel().getColumnCount() > 0) {
            jTPontosOnibus.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 360, 340));

        jBRemoverPonto.setText("Remover ponto");
        jPanel1.add(jBRemoverPonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 130, -1));

        jBConfirmar.setText("Confirmar");
        jBConfirmar.addActionListener(this::jBConfirmarActionPerformed);
        jPanel1.add(jBConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 120, -1));

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(this::jBCancelarActionPerformed);
        jPanel1.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 120, -1));

        jButton1.setText("Desfazer último ponto clicado");
        jButton1.setActionCommand("Desfazer último ponto clicado");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        JPRotas parent = (JPRotas) SwingUtilities.getAncestorOfClass(JPRotas.class, this);
        if (parent != null) {
            parent.exibirTabela();
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jRBPontoRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPontoRotaActionPerformed
        JPRotas parent = (JPRotas) SwingUtilities.getAncestorOfClass(JPRotas.class, this);
        if (parent != null) parent.setModoAtual(JPRotas.ModoEdicao.ROTA);
    }//GEN-LAST:event_jRBPontoRotaActionPerformed

    private void jRBPontoOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPontoOnibusActionPerformed
        JPRotas parent = (JPRotas) SwingUtilities.getAncestorOfClass(JPRotas.class, this);
        if (parent != null) parent.setModoAtual(JPRotas.ModoEdicao.ONIBUS);
    }//GEN-LAST:event_jRBPontoOnibusActionPerformed

    private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
        String nomeRota = jTextField1.getText();
    
        JPRotas parent = (JPRotas) SwingUtilities.getAncestorOfClass(JPRotas.class, this);
        if (parent != null) {
            List<GeoPosition> trajeto = parent.getPontosTrajeto();
            List<GeoPosition> paradas = parent.getPontosOnibus();

            if (nomeRota.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Preencha o nome da rota!");
                return;
            }
            if (trajeto.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Desenhe pelo menos um trajeto no mapa!");
                return;
            }

            // TODO: Chamar sua classe RotaDAO aqui passando os dados!
            System.out.println("Salvando Rota: " + nomeRota);
            System.out.println("Total de pontos do trajeto: " + trajeto.size());
            System.out.println("Total de paradas de ônibus: " + paradas.size());
        }
    }//GEN-LAST:event_jBConfirmarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JPRotas parent = (JPRotas) SwingUtilities.getAncestorOfClass(JPRotas.class, this);
        if (parent != null) {
            parent.desfazerUltimoPonto();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jBRemoverPonto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLCadastrarPontos;
    private javax.swing.JLabel jLNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBPontoOnibus;
    private javax.swing.JRadioButton jRBPontoRota;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTPontosOnibus;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
