/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.mycompany.chaponibus.admin.view.rotas;

import br.com.mycompany.chaponibus.admin.dao.RotaDAO;
import br.com.mycompany.chaponibus.admin.model.Rota;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ce498
 */
public class JPTabelaRotas extends javax.swing.JPanel {

    /**
     * Creates new form JPTabelaRotas
     */
    public JPTabelaRotas() {
        initComponents();
        carregarTabela();
        
        jTTabelaRotas.setRowHeight(30);
        jTTabelaRotas.setShowHorizontalLines(true);
        jTTabelaRotas.setShowVerticalLines(false);
        jTTabelaRotas.setGridColor(new Color(230, 235, 240));
        jTTabelaRotas.putClientProperty("FlatLaf.style", "showCellFocusIndicator: false");
        
        jTTabelaRotas.getTableHeader().setPreferredSize(new Dimension(0, 45));
        jTTabelaRotas.getTableHeader().putClientProperty("FlatLaf.style", 
                "background: #f1f3f5;" +
                "foreground: #212529;" +
                "font: bold 16;" +
                "separatorColor: #f1f3f5"
        );
    }
    
    public void carregarTabela() {
        try {
            RotaDAO dao = new RotaDAO();
            List<Rota> rotas = dao.listarTodas();

            DefaultTableModel modelo = (DefaultTableModel) jTTabelaRotas.getModel();
            modelo.setRowCount(0);

            for (Rota r : rotas) {
                modelo.addRow(new Object[]{ r.getId(), r.getNomeRota() });
            }

            jTTabelaRotas.getColumnModel().getColumn(0).setMinWidth(0);
            jTTabelaRotas.getColumnModel().getColumn(0).setMaxWidth(0);
            jTTabelaRotas.getColumnModel().getColumn(0).setWidth(0);

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar rotas: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTTabelaRotas = new javax.swing.JTable();

        setBackground(new java.awt.Color(244, 247, 249));
        setOpaque(false);

        jTTabelaRotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Rotas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTTabelaRotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTabelaRotasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTabelaRotas);
        if (jTTabelaRotas.getColumnModel().getColumnCount() > 0) {
            jTTabelaRotas.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTTabelaRotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTabelaRotasMouseClicked
        if (evt.getClickCount() == 2) { // Ao clicar duas vezes
            int linha = jTTabelaRotas.getSelectedRow();
            int idRota = (int) jTTabelaRotas.getValueAt(linha, 0);
            
            JPRotas parent = (JPRotas) javax.swing.SwingUtilities.getAncestorOfClass(JPRotas.class, JPTabelaRotas.this);
            if (parent != null) {
                parent.iniciarEdicao(idRota);
            }
        }
    }//GEN-LAST:event_jTTabelaRotasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTTabelaRotas;
    // End of variables declaration//GEN-END:variables
}
